name: Go Security Scan

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'branch1'

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # Set the Go version you are using

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL'
          format: 'table' # Output format (optional)
  docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: poonamkhichade720
          password: PoonamK123*
      
      - name: Build and Push container images
        uses: docker/build-push-action@v4.0.0
        id: build-and-push
        with:
          push: true
          tags: poonamkhichade720/app:latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
        
      - name: Sign the images with GitHub OIDC Token1
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: poonamkhichade720/app:latest
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
          
             
          
        
