name: Go Security Scan

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'branch1'

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # Set the Go version you are using

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL'
          format: 'table' # Output format (optional)

      - name: Build Docker Image
        run: docker build -t myorg/my-golang-app:${{ github.sha }} .
      
      - name: Push to Docker Hub
        if: success()
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push myorg/my-golang-app:${{ github.sha }}
